spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ms_test_db
    username: postgres
    password: postgres
  liquibase:
    change-log: liquibase/changelog-master.yml
    enabled: true
    drop-first: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


